#!/bin/sh
# 
# This is currently just a POSIX script to run 
# the ./layout.sh script in its own terminal window.
# 
# You may need to edit this script to make it work on 
# your system, terminal of choice, etc.
# 
# Eventually, the functionality of these scripts may be
# replaced with a compiled application, likely Rust.
# 
# Simple logging setup
log_file=$( dirname -- "$( readlink -f -- $0)")/ezxlayout.log 
log_file=/dev/null # Comment/remove this line to enable simple logging
#
echo "ezxlayout $(date -Ins) PID=$$ Enter" >> $log_file
my_dir=$( dirname -- "$( readlink -f -- $0)")
if [ -z "$DISPLAY" -o -z "$XAUTHORITY" ]; then 
   echo "ezxlayout $(date -Ins) PID=$$ X11 environment not set; try all users and X11 displays." >> $log_file
   for u in $(users); do # try displaying for all logged in users
      echo "ezxlayout $(date -Ins) PID=$$ for user=$u" >> $log_file
      if [ -f /home/${u}/.Xauthority ]; then # Can we find X11 secrects file
          echo "ezxlayout $(date -Ins) PID=$$ for /home/${u}/.Xauthority" >> $log_file
          for d in $(ls /tmp/.X11-unix | tr 'X' ':'); do # try on all X displays
             echo "ezxlayout $(date -Ins) PID=$$ for user=$u and DISPLAY=${d}" >> $log_file
             export DISPLAY=${d}
             export XAUTHORITY=/home/${u}/.Xauthority
             nohup xfce4-terminal --title "EZXLayout udev" --hide-menubar --hide-toolbar --execute ${my_dir}/layout.sh &
          done
      fi
   done
else # X11 environment is already set
   echo "ezxlayout $(date -Ins) PID=$$ X11 environment is already set" >> $log_file
   xfce4-terminal --title "EZXLayout" --hide-menubar --hide-toolbar --execute ${my_dir}/layout.sh 
fi
echo "ezxlayout $(date -Ins) PID=$$ Exiting" >> $log_file
